# Generated by Django 5.1.6 on 2025-03-11 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0007_alter_cliente_type_pf_pj'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoIrradianciaSolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='', max_length=200)),
                ('cidade', models.CharField(default='', max_length=200)),
                ('bairro', models.CharField(default='', max_length=200)),
                ('irradi_jan', models.FloatField(default=0, verbose_name='Irradiancia Janeiro')),
                ('irradi_fev', models.FloatField(default=0, verbose_name='Irradiancia Fevereiro')),
                ('irradi_mar', models.FloatField(default=0, verbose_name='Irradiancia Março')),
                ('irradi_abr', models.FloatField(default=0, verbose_name='Irradiancia Abril')),
                ('irradi_mai', models.FloatField(default=0, verbose_name='Irradiancia Maio')),
                ('irradi_jun', models.FloatField(default=0, verbose_name='Irradiancia Junho')),
                ('irradi_jul', models.FloatField(default=0, verbose_name='Irradiancia Julho')),
                ('irradi_ago', models.FloatField(default=0, verbose_name='Irradiancia Agosto')),
                ('irradi_set', models.FloatField(default=0, verbose_name='Irradiancia Setembro')),
                ('irradi_out', models.FloatField(default=0, verbose_name='Irradiancia Outubro')),
                ('irradi_nov', models.FloatField(default=0, verbose_name='Irradiancia Novembro')),
                ('irradi_dez', models.FloatField(default=0, verbose_name='Irradiancia Dezembro')),
            ],
            options={
                'verbose_name': 'Irradiancia Média',
                'verbose_name_plural': 'Irradiancias Médias',
            },
        ),
        migrations.CreateModel(
            name='CalculoSolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cons_jan', models.IntegerField(default=0, verbose_name='Consumo (kWh) Janeiro')),
                ('cons_fev', models.IntegerField(default=0, verbose_name='Consumo (kWh) Fevereiro')),
                ('cons_mar', models.IntegerField(default=0, verbose_name='Consumo (kWh) Março')),
                ('cons_abr', models.IntegerField(default=0, verbose_name='Consumo (kWh) Abril')),
                ('cons_mai', models.IntegerField(default=0, verbose_name='Consumo (kWh) Maio')),
                ('cons_jun', models.IntegerField(default=0, verbose_name='Consumo (kWh) Junho')),
                ('cons_jul', models.IntegerField(default=0, verbose_name='Consumo (kWh) Julho')),
                ('cons_ago', models.IntegerField(default=0, verbose_name='Consumo (kWh) Agosto')),
                ('cons_set', models.IntegerField(default=0, verbose_name='Consumo (kWh) Setembro')),
                ('cons_out', models.IntegerField(default=0, verbose_name='Consumo (kWh) Outubro')),
                ('cons_nov', models.IntegerField(default=0, verbose_name='Consumo (kWh) Novembro')),
                ('cons_dez', models.IntegerField(default=0, verbose_name='Consumo (kWh) Dezembro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Consumo Médio',
                'verbose_name_plural': 'Consumos Médios',
            },
        ),
        migrations.CreateModel(
            name='CalculoPotenciaGeracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendimento', models.IntegerField(default=100, verbose_name='Eficiência do Sistema %')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('irradi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculoirradianciasolar', verbose_name='Irradiação Solar')),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculosolar', verbose_name='Consumo Base')),
            ],
            options={
                'verbose_name': 'Potência de Geração Necessária ',
                'verbose_name_plural': 'Potências de Geração Necessárias',
            },
        ),
        migrations.CreateModel(
            name='CalcPotenciaAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Equipamento')),
                ('pot', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Potência do equipamento (Watts)')),
                ('horas', models.FloatField(blank=True, null=True, verbose_name='Horas de Uso por dia')),
                ('minutos', models.FloatField(blank=True, null=True, verbose_name='Minutos de Uso por dia')),
                ('dias', models.FloatField(blank=True, null=True, verbose_name='Dias uso mês')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculosolar')),
            ],
            options={
                'verbose_name': 'Adição de consumo pela Potência do equipamento',
                'verbose_name_plural': 'Adições de consumo pela Potência dos equipamentos',
            },
        ),
        migrations.CreateModel(
            name='AdicaoPotenciaKWHMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Equipamento')),
                ('consumo', models.FloatField(blank=True, null=True, verbose_name='Consumo (kWh/mes)')),
                ('horas', models.FloatField(blank=True, null=True, verbose_name='Horas de Uso por dia')),
                ('minutos', models.FloatField(blank=True, null=True, verbose_name='Minutos de Uso por dia')),
                ('dias', models.FloatField(blank=True, null=True, verbose_name='Dias uso mês')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculosolar')),
            ],
            options={
                'verbose_name': 'Adição de consumo por kWh/mes do equipamento',
                'verbose_name_plural': 'Adições de consumo por kWh/mes dos equipamentos',
            },
        ),
        migrations.CreateModel(
            name='QntPaineis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potpainel', models.IntegerField(default=0, verbose_name='Potencia do Painel (W)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('potgeracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculopotenciageracao', verbose_name='Potência de Geração')),
            ],
            options={
                'verbose_name': 'Quantdade de Painel Necessário ',
                'verbose_name_plural': 'Quantdade de Painéis Necessários',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GeracaoPrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paineisdesejados', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Painéis Desejada')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('irrad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculoirradianciasolar', verbose_name='Irradiância Local')),
                ('rend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculopotenciageracao', verbose_name='Eficiência')),
                ('potsist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.qntpaineis', verbose_name='Numero ideal de Painéis no Sistema')),
            ],
        ),
    ]
