# Generated by Django 5.1.6 on 2025-03-05 23:16

import clientes.models
import clientes.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Cliente')),
                ('doc', models.CharField(max_length=14, unique=True, verbose_name='CPF/CNPJ')),
                ('type_pf_pj', models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('PF', 'Pessoa Fisica')], default='PF', max_length=2)),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('phone1', models.CharField(max_length=14, verbose_name='Contato 1')),
                ('phone2', models.CharField(blank=True, max_length=14, null=True, verbose_name='Contato 2')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='ContaClienteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archives', models.FileField(upload_to=clientes.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif']), clientes.validators.validate_file_mimetype, clientes.validators.validate_file_size], verbose_name='Arquivo (PDF ou imagem)')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='clientes.cliente')),
            ],
        ),
    ]
