# Generated by Django 5.1.6 on 2025-03-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='type_pf_pj',
            field=models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('PF', 'Pessoa Fisica')], default='PF', max_length=2, verbose_name='PF ou PJ'),
        ),
    ]
