# Generated by Django 5.1.6 on 2025-03-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_type_pf_pj'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='coord_s',
            field=models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='Coordenada Sul'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='coord_w',
            field=models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='Coordenada Oeste'),
        ),
    ]
