# Generated by Django 5.1.6 on 2025-03-06 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_coord_s_cliente_coord_w'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='postal_code',
            field=models.CharField(default='-', max_length=8, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='register_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='cliente',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='street',
            field=models.CharField(default='-', max_length=100, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='street_number',
            field=models.CharField(default='-', max_length=100, verbose_name='Numero'),
        ),
    ]
