# Generated by Django 5.1.6 on 2025-03-06 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_bairro_cliente_city_cliente_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='register_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data de Cadastro'),
        ),
    ]
