# Generated by Django 5.1.6 on 2025-03-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='coord_s',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='Coordenada Sul'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='coord_w',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='Coordenada Oeste'),
        ),
    ]
