# Generated by Django 5.1.6 on 2025-03-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_cliente_type_pf_pj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='phone1',
            field=models.CharField(max_length=11, verbose_name='Contato 1'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='phone2',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Contato 2'),
        ),
    ]
